version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENV_VAR=value
    volumes:
      - ./src:/usr/src/app
